name: chroma
description: A simple library for manipulating colors in Dart.
version: 0.1.0
homepage: https://github.com/jimmyff/chroma

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  vector_math: ^2.1.0
  logging: any
  image: ^3.0.7

dev_dependencies:
  test: any
