name: chroma
description: A simple library for manipulating colors in Dart.
version: 0.1.2
homepage: https://github.com/jimmyff/chroma

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  vector_math: ^2.1.0
  logging: ^1.1.1
  image: ^4.0.15

dev_dependencies:
  test: any
